### ISSUE TITLE
Fix flaky ScrollZoomHandler unit test

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#10364]
`ScrollZoomHandler` unit tests are flaky and fail on CI pretty frequently recently. [Example failing job](https://app.circleci.com/pipelines/github/mapbox/mapbox-gl-js/5784/workflows/db692762-5ff1-4433-a660-2a6540e9ab7f/jobs/78875).

```
ScrollZoomHandler > Zooms for single mouse wheel tick with non-magical deltaY
  not ok test unfinished

...
ScrollZoomHandler
  not ok test count !== plan
    --- wanted
    +++ found
    -2
    +9
    results:
      ok: false
      count: 9
      pass: 1
      fail: 8
      bailout: false
      todo: 0
      skip: 0
      plan:
        start: 1
        end: 2
        skipAll: false
        skipReason: ''
        comment: ''
      failures:
        - ok: false
          id: 2
          time: 738.438
          name: Zooms for single mouse wheel tick with non-magical deltaY
        - ok: false
          id: 3
          name: 'child test left in queue: t.test Zooms for multiple mouse wheel ticks'
          parent: ScrollZoomHandler
        - ok: false
          id: 4
          name: 'child test left in queue: t.test Terrain'
          parent: ScrollZoomHandler
        - ok: false
          id: 5
          name: >-
            child test left in queue: t.test Gracefully ignores wheel events with
            deltaY: 0
          parent: ScrollZoomHandler
        - ok: false
          id: 6
          name: >-
            child test left in queue: t.test Gracefully handle wheel events that
            cancel each other out before the first scroll frame
          parent: ScrollZoomHandler
        - ok: false
          id: 7
          name: >-
            child test left in queue: t.test does not zoom if preventDefault is
            called on the wheel event
          parent: ScrollZoomHandler
        - ok: false
          id: 8
          name: >-
            child test left in queue: t.test emits one movestart event and one
            moveend event while zooming
          parent: ScrollZoomHandler
        - ok: false
          id: 9
          name: >-
            child test left in queue: t.test emits one zoomstart event and one
            zoomend event while zooming
          parent: ScrollZoomHandler
```

cc @ansis
