### ISSUE TITLE
allow changing Mapbox logo/wordmark location after map initialisation

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#10539]
## Motivation

GL JS allows developers to choose which corner the Mapbox logo/wordmark appears, however this can only be configured once at map initialisation.

When designing a page with a Mapbox map, the developer might which to place the wordmark in one position on wide screens (desktop) and a different position on narrow screens (mobile). Currently that's not easy to achieve.

## Design Alternatives

One option is to provide a setter method for the logo position so it can be altered at any time after map initialisation.

Another option is to make the LogoControl part of the public API, thereby allowing it to be manually added as a control. Developers would then add/remove it to move it into a different corner.

**Comment by andrewharvey** [comment]
The workaround I'm using is

```js
// add the logo to the bottom right
const map = new mapboxgl.Map({
   logoPosition: 'bottom-right'
})
// duplicate logo to the bottom left
map.addControl(map._logoControl, 'bottom-left')
```

```css
/* toggle which logo is shown based on screen size */
@media (min-width: 600px) {
  .mapboxgl-ctrl-bottom-left .mapboxgl-ctrl-logo {
    display: none;
  }
}
@media (max-width: 599px) {
  .mapboxgl-ctrl-bottom-right .mapboxgl-ctrl-logo {
    display: none;
  }
}
```
