### ISSUE TITLE
Custom pop up not rotating when the map rotates

### ISSUE THREAD

**Issue by jonaaldas** [mapbox/mapbox-gl-js#12893]
👋 Hello Mapbox Community,

I'm experiencing an issue with customizing the behavior of the Mapbox popup tip. Specifically, the problem is that my custom tip doesn't rotate in sync with the map. I've attempted to apply a CSS transform property to adjust its orientation, but unfortunately, that doesn't seem to work.

📷 Issue Visualized:
(Please refer to the attached image for a clear understanding of the issue.)

📝 What I've Tried:
I'm adding popups programmatically and have also used the following CSS to style the popup tip:

```CSS
.mapboxgl-popup-tip {
  width: 20px !important;
  height: 20px !important;
  background: linear-gradient(to right, red 50%, green 50%) !important;
  clip-path: polygon(50% 100%, 0% 0%, 100% 0%) !important;
}
```

Despite these custom styles, the tip refuses to rotate when the map itself is rotated, essentially disregarding any transform styles that I try to apply.

I'd really appreciate any insights or solutions to this challenge. Has anyone faced similar issues or has advice on how to successfully apply the transform property to the Mapbox popup tip?

Thanks in advance for your assistance! 🙏

![image](https://github.com/mapbox/mapbox-gl-js/assets/12662909/82ce56a0-7d6b-4b0a-9438-326307073af6)
