### ISSUE TITLE
Let mapboxgl-popup-tip has a real border

### ISSUE THREAD

**Issue by Stupidism** [mapbox/mapbox-gl-js#5919]
## Motivation

I wanted to customize Popup style to make the small triangle has a nice border with my content together.
However, I found it fulfilled with `tricky padding`, which means I can't overwrite the css to add a border for it.  

## Design Alternatives

I couldn't find a way to `add border on padding` anyway.

## Design

Use `rotated square` to fulfill small triangle of Popup instead of `tricky padding`. 

Advantages: 
- The triangle has real borders then.
- Maybe no need to switch among padding-`top|bottom|left|right` any more, in the condition of auto-adjustment of position.

Potential Drawbacks:
- Overlapped square over window?

### Mock-Up

Looks like exactly the same as before.

### Concepts

- More customizable popup triangle?
- Basic css knowledge is enough.

### Implementation

In css: 
```css
.mapboxgl-popup-tip {
  width: 14.14px; /* 20/1.414 */
  height: 14.14px; /* 20/1.414 */
  transform:rotate(45deg);
}
```
