### ISSUE TITLE
"ctrl-shrink" svg is not defined

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#8944]
@kkaefer When building CSS in the current `master` (after #8874), there's a warning:

```
⚠  "ctrl-shrink" svg is not defined [postcss-inline-svg]
```

If you look into generated `mapbox-gl.css`, the corresponding class is not processed, resulting in an invalid CSS rule:

```css
.mapboxgl-ctrl button.mapboxgl-ctrl-shrink .mapboxgl-ctrl-icon{
    background-image:svg-inline(ctrl-shrink)
}
```
