### ISSUE TITLE
Mapbox Control CSS for button hovering

### ISSUE THREAD

**Issue by paparent** [mapbox/mapbox-gl-js#9760]
**mapbox-gl-js version**: 1.9.1 (same in latest)

### Question

Hi, I'd like to have some custom overlays on the map and I thought that using `map.addControl` API would be the way to go.

Unfortunately, CSS has the following instruction: https://github.com/mapbox/mapbox-gl-js/blob/v1.10.1/src/css/mapbox-gl.css#L150-L152

```css
.mapboxgl-ctrl button:not(:disabled):hover {
    background-color: rgba(0, 0, 0, 0.05);
}
```

So if in my overlay I've for example buttons, styled with bootstrap, I lose its hover effect.

Is Control intended to be used only for controls, or it can be for map overlay with some custom HTML on it? Is there a way to either reset the effect of the button or better: Scope better this styling for the type of controls.

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/markers/#icontrol
